name: wallet_whitelabel
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/williancm812/wallet_whitelabel.git

flutter:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


