name: wallet_whitelabel
description: A new Flutter package project.
version: 0.0.7
homepage: https://github.com/williancm812/wallet_whitelabel.git

flutter:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  auto_size_text: ^3.0.0
  qr_flutter: ^4.0.0
  dio: ^4.0.4
  intl: ^0.17.0
  jiffy: ^4.1.0
  supercharged: ^2.1.1
  provider: ^6.0.1
  share_plus: ^3.0.4
  google_fonts: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


